version: "3.7"
services:

  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.6
    container_name: logstash
    volumes:
      - ./conf/cloudfront.conf:/usr/share/logstash/config/cloudfront.conf
      - ./conf/cloudfront.template.json:/usr/share/logstash/config/cloudfront.template.json
      - ./data/logstash/files:/files
      - ./data/logstash/logs:/logs
    environment:
      - PIPELINE_WORKERS=8
      - "LS_JAVA_OPTS=-Xmx2g -Xms2g"
    command: "logstash -f /usr/share/logstash/config/cloudfront.conf"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.8.6
  #   container_name: kibana
  #   environment:
  #     - ELASTICSEARCH=elasticsearch
  #   ports:
  #     - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
