version: "3.7"
services:

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash
    volumes:
      - ./conf/cloudfront.conf:/usr/share/logstash/config/cloudfront.conf
      - ./conf/cloudfront.template.json:/usr/share/logstash/config/cloudfront.template.json
      - ./data/logstash/files:/files
      - ./data/logstash/logs:/logs
    environment:
      - PIPELINE_WORKERS=8
      - "LS_JAVA_OPTS=-Xmx2g -Xms2g"
    command: "logstash -f /usr/share/logstash/config/cloudfront.conf"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH=elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - search.max_buckets=90000
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
